imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: resources/sonata.yml }
    - { resource: resources/user.yml }
    - { resource: resources/media.yml }
    - { resource: resources/search.yml }


framework:
    esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        flickr_api_key: %flickr_api_key%
        vk_api_key:     %vk_api_key%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ SIPResourceBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        dql:
            datetime_functions:
                month: SIP\ResourceBundle\DQL\Month
                year: SIP\ResourceBundle\DQL\Year
                rand: SIP\ResourceBundle\DQL\Rand

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            loggable: true
            sortable: true

sensio_framework_extra:
    view:    { annotations: true }
    router:  { annotations: true }

knp_menu:
    twig:
        template: SIPResourceBundle:Menu:menu.html.twig

fpn_tag:
    model:
        tag_class:     SIP\ResourceBundle\Entity\Tag\Tag
        tagging_class: SIP\ResourceBundle\Entity\Tag\Tagging

genemu_form:
    select2:
        enabled: true
        configs:
            width: 100%
            allowClear: true
    autocomplete: ~