sonata_media:
    class:
        media:             SIP\ResourceBundle\Entity\Media\Media
        gallery:           SIP\ResourceBundle\Entity\Media\Gallery
        gallery_has_media: SIP\ResourceBundle\Entity\Media\GalleryHasMedia
#        category:          SIP\ResourceBundle\Entity\Classification\Category
    default_context: default
    db_driver: doctrine_orm
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image
            formats:
                small: { width: 100 , quality: 100}
                big:   { width: 500 , quality: 100}
        event:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 100 , quality: 100}
                big:   { width: 500 , quality: 100}
                list: { width: 215 , quality: 100}
        news:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 100 , quality: 100}
                big:   { width: 500 , quality: 100}
                list: { width: 215 , quality: 100}

        designer:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 100 , quality: 100}
                big:   { width: 500 , quality: 100}
                list: { width: 215 , quality: 100}
        brand:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 100 , quality: 100}
                big:   { width: 500 , quality: 100}
                list: { width: 215 , quality: 100}

        manufacturer:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 100 , quality: 100}
                big:   { width: 500 , quality: 100}
                list: { width: 215 , quality: 100}

        mainspot:
            providers:
                - sonata.media.provider.image
            formats:
                main: { width: 1000, height: 400, quality: 100}
                left: { width: 392, height: 251, quality: 100}
                right: { width: 250, height: 250, quality: 100}
                small: { width: 100 , quality: 100}

        designer_gallery:
            providers:
                - sonata.media.provider.image
            formats:
                gallery: { width: 190, quality: 100}
                small: { width: 100 , quality: 100}
                big:   { width: 500 , quality: 100}

        banner:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 100 , quality: 100}
                big:   { width: 500 , quality: 100}
    cdn:
        server:
            path: /uploads/media

    filesystem:
            local:
                directory:  %kernel.root_dir%/../web/uploads/media
                create:     false